apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  UID: YWRtaW4=
  PASSWORD: YWRtaW4=
  SECRET: aGVsbG8=
  EMAILUSERNAME: aWNwYWlyd2F5c0BnbWFpbC5jb20=
  EMAILPASSWORD: LmljcGFpcndheXM=
  