apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: signupsvc 
spec:
 replicas: 3
 template:
   metadata:
     name: signupsvc
     labels:
       app: signupsvc
   spec:
     containers:
       - name: signupsvcluster
         image: "mycluster.icp:8500/default/signup-microservice:latest" 
         imagePullPolicy: Always
         env:
          - name: UID
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: UID
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: PASSWORD
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: SECRET
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: env-database
                key: NODE_ENV
          - name: DATABASE
            valueFrom:
              configMapKeyRef:
                name: env-database
                key: DATABASE
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: env-database
                key: PORT
          - name: HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: env-database
                key: HOSTNAME
          - name: PROTOCOL
            valueFrom:
              configMapKeyRef:
                name: env-database
                key: PROTOCOL
         ports:
         - containerPort: 3004

        #  livenessProbe:
        #     httpGet:
        #       path: /healthz
        #       port: 8080
        #       scheme: HTTP
        #     initialDelaySeconds: 30
        #     periodSeconds: 30
        #  readinessProbe:
        #     httpGet:
        #       path: /readiness
        #       port: 8080
        #       scheme: HTTP
        #     initialDelaySeconds: 30
        #     periodSeconds: 30     
---
apiVersion: v1
kind: Service
metadata:
 name: signupsvc
 labels:
   app: signupsvc
spec:
 type: NodePort
 selector:
   app: signupsvc
 ports:
  - protocol: TCP
    name: signupsvc
    port: 3004
    targetPort: 3004
    nodePort: 30094
    


